version: '3.11'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: app:fastapi
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_URL: ${REDIS_URL}
      SECRET_TOKEN: ${SECRET_TOKEN}

  celery:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery
    command: celery -A src.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_URL: ${REDIS_URL}
      CELERY_BROKER_URL: ${REDIS_URL}/1
      SECRET_TOKEN: ${SECRET_TOKEN}
